#!/usr/bin/env node
// liz.studio factory CLI: builds apps, runs them as systemd services, and
// routes them through a Cloudflare Tunnel, all driven by factory.json.
//
//   node scripts/factory.mjs build <app|all>
//   node scripts/factory.mjs install <app|all>   build + install/restart the systemd service
//   node scripts/factory.mjs deploy <app|all>    git pull, then install
//   node scripts/factory.mjs tunnel-config       write /etc/cloudflared/config.yml from factory.json
//   node scripts/factory.mjs status
//
// Env: LIZ_LISTEN_HOST (default 127.0.0.1) - set 0.0.0.0 to also expose app ports
// directly, e.g. before the tunnel is live.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const config = JSON.parse(fs.readFileSync(path.join(ROOT, "factory.json"), "utf8"));
const user = os.userInfo().username;
const host = process.env.LIZ_LISTEN_HOST ?? "127.0.0.1";

const run = (cmd, args, opts = {}) => execFileSync(cmd, args, { stdio: "inherit", ...opts });
const sudoWrite = (file, content) =>
  execFileSync("sudo", ["tee", file], { input: content, stdio: ["pipe", "ignore", "inherit"] });
const unitName = (app) => `liz-${app.name}.service`;

function apps(which) {
  if (!which) fail("Name an app (or 'all').");
  if (which === "all") return config.apps;
  const app = config.apps.find((a) => a.name === which);
  if (!app) fail(`No app named '${which}' in factory.json.`);
  return [app];
}

function fail(msg) {
  console.error(msg);
  process.exit(1);
}

function build(app) {
  const cwd = path.join(ROOT, app.dir);
  console.log(`\n▸ Building ${app.name} (${app.path})`);
  run("npm", ["ci"], { cwd });
  run("npm", ["run", "build"], { cwd, env: { ...process.env, BASE_PATH: app.path } });
}

function install(app) {
  build(app);
  const cwd = path.join(ROOT, app.dir);
  const unit = `[Unit]
Description=liz.studio app: ${app.name}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${user}
WorkingDirectory=${cwd}
Environment=NODE_ENV=production
# next start re-reads next.config.ts, so the base path must be set at runtime too.
Environment=BASE_PATH=${app.path}
ExecStart=${process.execPath} ${cwd}/node_modules/next/dist/bin/next start -p ${app.port} -H ${host}
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
`;
  sudoWrite(`/etc/systemd/system/${unitName(app)}`, unit);
  run("sudo", ["systemctl", "daemon-reload"]);
  run("sudo", ["systemctl", "enable", unitName(app)]);
  run("sudo", ["systemctl", "restart", unitName(app)]);
  console.log(`✓ ${app.name} running on ${host}:${app.port}${app.path}`);
}

function tunnelConfig() {
  const credDir = path.join(os.homedir(), ".cloudflared");
  const creds = fs.existsSync(credDir)
    ? fs.readdirSync(credDir).filter((f) => /^[0-9a-f-]{36}\.json$/.test(f))
    : [];
  if (creds.length !== 1) {
    fail(
      `Expected one tunnel credentials file in ${credDir}, found ${creds.length}.\n` +
        `Run: cloudflared tunnel login && cloudflared tunnel create ${config.tunnel}`,
    );
  }
  const id = creds[0].replace(".json", "");
  const escape = (p) => p.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const rules = config.apps
    .map(
      (a) => `  - hostname: ${config.domain}
    path: ^${escape(a.path)}(/.*)?$
    service: http://127.0.0.1:${a.port}`,
    )
    .join("\n");
  const yml = `# Generated by scripts/factory.mjs from factory.json. Do not edit by hand.
tunnel: ${id}
credentials-file: ${path.join(credDir, creds[0])}

ingress:
${rules}
  - service: http_status:404
`;
  run("sudo", ["mkdir", "-p", "/etc/cloudflared"]);
  sudoWrite("/etc/cloudflared/config.yml", yml);
  console.log(yml);
  console.log("✓ Wrote /etc/cloudflared/config.yml");
}

function status() {
  for (const app of config.apps) {
    let state = "not installed";
    try {
      state = execFileSync("systemctl", ["is-active", unitName(app)], { encoding: "utf8" }).trim();
    } catch (e) {
      state = e.stdout?.toString().trim() || state;
    }
    console.log(`${app.name.padEnd(16)} ${state.padEnd(10)} :${app.port}  https://${config.domain}${app.path}`);
  }
}

const [cmd, arg] = process.argv.slice(2);
switch (cmd) {
  case "build":
    apps(arg).forEach(build);
    break;
  case "install":
    apps(arg).forEach(install);
    break;
  case "deploy":
    run("git", ["pull", "--ff-only"], { cwd: ROOT });
    apps(arg).forEach(install);
    break;
  case "tunnel-config":
    tunnelConfig();
    break;
  case "status":
    status();
    break;
  default:
    fail("Usage: node scripts/factory.mjs <build|install|deploy> <app|all> | tunnel-config | status");
}
